"""Schemas and constants for interview records."""

from __future__ import annotations


SESSION_STATUS_OPEN = "open"
SESSION_STATUS_CLOSED = "closed"
SESSION_STATUS_ARCHIVED = "archived"
SESSION_STATUSES = {SESSION_STATUS_OPEN, SESSION_STATUS_CLOSED, SESSION_STATUS_ARCHIVED}

CREATED_REASON_MANUAL_PREP = "manual_prep"
CREATED_REASON_STATUS_IN_PROCESS = "status_in_process"
CREATED_REASON_TEAMS_MEETING = "teams_meeting"
CREATED_REASON_CODEX_PREP = "codex_prep"
CREATED_REASON_AD_HOC_ASSIST = "ad_hoc_assist"
CREATED_REASONS = {
    CREATED_REASON_AD_HOC_ASSIST,
    CREATED_REASON_MANUAL_PREP,
    CREATED_REASON_STATUS_IN_PROCESS,
    CREATED_REASON_TEAMS_MEETING,
    CREATED_REASON_CODEX_PREP,
}

PREP_EVENT_PREDICTED_QUESTION = "predicted_question"
PREP_EVENT_ANSWER_STRATEGY = "answer_strategy"
PREP_EVENT_SKILL_GAP = "skill_gap"
PREP_EVENT_PROJECT_STORY = "project_story"
PREP_EVENT_LEARNING_PLAN = "learning_plan"
PREP_EVENT_RESUME_SIGNAL = "resume_signal"
PREP_EVENT_NOTE = "note"
PREP_EVENT_TYPES = {
    PREP_EVENT_PREDICTED_QUESTION,
    PREP_EVENT_ANSWER_STRATEGY,
    PREP_EVENT_SKILL_GAP,
    PREP_EVENT_PROJECT_STORY,
    PREP_EVENT_LEARNING_PLAN,
    PREP_EVENT_RESUME_SIGNAL,
    PREP_EVENT_NOTE,
}

SPEAKER_INTERVIEWER = "interviewer"
SPEAKER_CANDIDATE = "candidate"
SPEAKER_ASSISTANT = "assistant"
SPEAKER_UNKNOWN = "unknown"
SPEAKERS = {SPEAKER_INTERVIEWER, SPEAKER_CANDIDATE, SPEAKER_ASSISTANT, SPEAKER_UNKNOWN}

TEXT_TYPE_QUESTION = "question"
TEXT_TYPE_ANSWER = "answer"
TEXT_TYPE_FOLLOWUP = "followup"
TEXT_TYPE_NOTE = "note"
TEXT_TYPES = {TEXT_TYPE_QUESTION, TEXT_TYPE_ANSWER, TEXT_TYPE_FOLLOWUP, TEXT_TYPE_NOTE}

SOURCE_MANUAL = "manual"
SOURCE_CODEX = "codex"
SOURCE_TEAMS = "teams"
SOURCE_TRANSCRIPT = "transcript"
SOURCES = {SOURCE_MANUAL, SOURCE_CODEX, SOURCE_TEAMS, SOURCE_TRANSCRIPT}

ADOPTION_ADOPTED = "adopted"
ADOPTION_PARTIALLY_ADOPTED = "partially_adopted"
ADOPTION_IGNORED = "ignored"
ADOPTION_UNKNOWN = "unknown"
ADOPTION_STATUSES = {
    ADOPTION_ADOPTED,
    ADOPTION_PARTIALLY_ADOPTED,
    ADOPTION_IGNORED,
    ADOPTION_UNKNOWN,
}

EVIDENCE_PREDICTED_QUESTION_HIT = "predicted_question_hit"
EVIDENCE_UNEXPECTED_QUESTION = "unexpected_question"
EVIDENCE_SKILL_GAP = "skill_gap"
EVIDENCE_RESUME_SIGNAL = "resume_signal"
EVIDENCE_COMPANY_SIGNAL = "company_signal"
EVIDENCE_ANSWER_QUALITY_SIGNAL = "answer_quality_signal"
EVIDENCE_PREPARATION_GAP = "preparation_gap"
EVIDENCE_TYPES = {
    EVIDENCE_PREDICTED_QUESTION_HIT,
    EVIDENCE_UNEXPECTED_QUESTION,
    EVIDENCE_SKILL_GAP,
    EVIDENCE_RESUME_SIGNAL,
    EVIDENCE_COMPANY_SIGNAL,
    EVIDENCE_ANSWER_QUALITY_SIGNAL,
    EVIDENCE_PREPARATION_GAP,
}
